# Generated by Django 5.2.17 on 2026-08-17 10:19

import datetime
import django.db.models.deletion
import uuid_extensions.uuid7
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangopress_pages", "0002_page_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="pagecontenttype",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="page",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 8, 17, 10, 19, 35, 732358, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="page",
            name="first_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="has_unpublished_changes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="last_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="live",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="slug",
            field=models.SlugField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="page",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="PageRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_extensions.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.JSONField()),
                ("title", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="djangopress_pages.page",
                    ),
                ),
            ],
            options={
                "db_table": "djangopress_pagerevision",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="page",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="djangopress_pages.pagerevision",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="live_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="djangopress_pages.pagerevision",
            ),
        ),
    ]
